 
"that should be two seperate tokens" 
withlet+ "should be an identifier" 
with and let.u
let x = nil if x + y - z <> 17 then 
as123 = 12 else end.

"I am a string and this should just print out and after me comes a print token"  print 

if isNil x then print "hello" else (*lets comment this line out*) 
in 
fun #x
"this is going to be a tail"
#
"head" !a
a@b
x = nil
x.yx
let y with x be x+y-7+as7675d