 readstring (*readint (*print (*isnil (*! (*# (*@ (*nil (*. (*with let 
+ - * / ( ) & | = <> <*) >*) <=*) >=*) if*) then*) else*) lambda*) fun*) ,*) in*)"
(* readstring (*readint (*print (*isnil (*! (*# (*@ (*nil (*. (*with (*let 
+ - * / ( ) & | = <> <*) >*) <=*) >=*) if*) then*) else*) lambda*) fun*) ,*) in*)
"Input: (* (*This should break it on line 62*)"
(* (*This should break it on line 62*)
